const mockEvents = {
  city: {
    id: 80001,
    city: 'Arvada',
    lat: 39.8,
    lon: -105.09,
    state: 'CO',
    country: 'us',
    zip: '80001',
    member_count: 1649
  },
  events: [
    {
      local_time: '11:30',
      local_date: '2019-10-27',
      link: 'https://www.meetup.com/The-Denver-Active-50-or-Better-Social-Group/events/264011982/',
      visibility: 'public_limited',
      group: {
        created: 1238538068000,
        name: 'The Denver 50 and Better Social Group',
        id: 1423005,
        join_mode: 'approval',
        lat: 39.72999954223633,
        lon: -104.97000122070312,
        urlname: 'The-Denver-Active-50-or-Better-Social-Group',
        who: 'Fun loving active adults',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      waitlist_count: 3,
      yes_rsvp_count: 40,
      duration: 7200000,
      time: 1572197400000,
      utc_offset: -21600000,
      name: 'Witches Tea - Warlocks Are Welcome Too ($40.50 per person)',
      id: '264011982'
    },
    {
      local_time: '12:00',
      local_date: '2019-12-05',
      link: 'https://www.meetup.com/Jeffco-Womens-Hiking-Meetup/events/265594758/',
      visibility: 'public_limited',
      group: {
        created: 1358457526000,
        name: 'Jeffco Women\'s Hiking Meetup',
        id: 6711572,
        join_mode: 'open',
        lat: 39.709999084472656,
        lon: -105.2300033569336,
        urlname: 'Jeffco-Womens-Hiking-Meetup',
        who: 'Mountain Mamas',
        localized_location: 'Golden, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      waitlist_count: 3,
      yes_rsvp_count: 15,
      duration: 10800000,
      time: 1575572400000,
      utc_offset: -25200000,
      name: 'Jeffco Women\'s Hiking Holiday Get Together',
      id: '265594758'
    },
    {
      created: 1565108199000,
      duration: 28800000,
      id: '263778772',
      name: 'DENVER HACKTOBERFEST | Web Dev & Design Hackathon | Fall 2019',
      rsvp_limit: 60,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1571493600000,
      local_date: '2019-10-19',
      local_time: '08:00',
      updated: 1570464080000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 19,
      venue: {
        id: 26110450,
        name: 'SecureSet Denver',
        lat: 39.75645065307617,
        lon: -104.99102783203125,
        repinned: true,
        address_1: '2228 Blake St #100',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '80205',
        state: 'CO'
      },
      group: {
        created: 1488837707000,
        name: 'Bootcampers Collective <> Co-op for Jr. Devs',
        id: 22799861,
        join_mode: 'open',
        lat: 39.70000076293945,
        lon: -105.08000183105469,
        urlname: 'Bootcampers-Collective',
        who: 'Bootcampers',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/Bootcampers-Collective/events/263778772/',
      description: '<p>Bootcampers Collective is proud to announce our next official Open Source Hackathon of 2019! We would like to invite members of the Colorado coding community to join us in this endeavor.</p> <p>Hacktoberfest® is open to everyone in our global community. Whether you’re a developer, student learning to code, event host, or company of any size, you can help drive growth of open source and make positive contributions to an ever-growing community. All backgrounds and skill levels are encouraged to complete the challenge. | Presented by DigitalOcean</p> <p>More info: hacktoberfest.digitalocean.com</p> <p>Address: SecureSet Academy, 2228 Blake St #100, Denver, CO<br/>Timing: 8:00am to 4:00pm</p> <p>Agenda:<br/>8:00am - Doors open<br/>9:00am - Welcome, Orientation, Break into teams<br/>12:00pm - Lunch<br/>3:00pm - Final Wrap-up, Debrief<br/>4:00pm - Close up shop</p> <p>Food &amp; beverages will be provided.</p> <p>Hackathons are a great opportunity for our members to gain resume-worthy experience working on open-source code for the community. Minimal experience required. ALL ARE WELCOME.</p> <p>www.bootcamperscollective.com/hackathon</p> <p>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</p> <p>Code of Conduct: *</p> <p>1. Be inclusive: We welcome and support people of all backgrounds and identities. This includes, but is not limited to members of any sexual orientation, gender identity and expression, race, ethnicity, culture, national origin, social and economic class, educational level, color, immigration status, sex, age, size, family status, political belief, religion, and mental and physical ability.<br/>2. Be considerate: Your decisions will affect other participants, and you should take those consequences into account when making decisions.<br/>3. Be respectful: We won\'t all agree all the time, but disagreement is no excuse for disrespectful behavior. Treat others, yourself, and venues with dignity.<br/>4. Choose your words carefully: Always conduct yourself professionally. Be kind to others. Harassment and exclusionary behavior aren\'t acceptable. This includes, but is not limited to: threats of violence, discriminatory jokes and language, sharing sexually explicit or violent material via electronic devices or other means, Personal insults, and Unwelcome sexual attention.<br/>5. Make differences into strengths: We can find strength in diversity. Focus on resolving issues and learning from mistakes.</p> <p>* BY ATTENDING OUR EVENTS YOU AGREE TO ABIDE BY THE CODE OF CONDUCT. WE RESERVE THE RIGHT TO TERMINATE INDIVIDUAL ATTENDANCE FOR VIOLATION OF OUR TERMS AND CONDITIONS.</p> <p>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</p> <p>About us:<br/>Bootcampers Collective is dedicated to providing web developers with experiential learning opportunities to produce code that helps small businesses around Colorado. Join us regardless of your experience level and have fun along the way.</p>',
      how_to_find_us: 'Ring the doorbell if it\'s not open',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1548949675000,
      duration: 10800000,
      id: 'xrfkbryznbmc',
      name: 'Monthly DenverScript Meetup',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1571788800000,
      local_date: '2019-10-22',
      local_time: '18:00',
      updated: 1570114939000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 40,
      venue: {
        id: 25156751,
        name: 'Code Talent',
        lat: 39.76769256591797,
        lon: -104.97679138183594,
        repinned: true,
        address_1: '3412 Blake St',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '',
        state: 'CO'
      },
      group: {
        created: 1422906650000,
        name: 'DenverScript',
        id: 18406024,
        join_mode: 'open',
        lat: 39.75,
        lon: -104.98999786376953,
        urlname: 'DenverScript',
        who: 'Scriptonites',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/DenverScript/events/xrfkbryznbmc/',
      description: '<p>6:15 pm: Intro and What\'s going on in JavaScript Land? (20min)</p> <p>We\'ll be talking about new/exciting things going on in the industry. If you have something you think we should mention, feel free to tweet us @DenverScript (twitter.com/denverscript).</p> <p>6:35 pm: Job Announcements</p> <p>Anyone with a job opening can come up to the front and announce it to the group.</p> <p>6:45 pm: Shorter Presentation(8 - 10min):</p> <p>Decoupling Child from Parent - Phil Lucks</p> <p>Should a parent component care about when a child component renders, or should the child own itself and tell the parent to MYOB? This topic will cover the pros &amp; cons of coupled components and why you may choose one over the other. Ideally, the audience will participate too so everyone can learn from the experiences of others.</p> <p>Phil has been working as a Front-End Engineer for over 3 years. If I\'m lucky I remember the code I wrote from 1 week ago.</p> <p>7:00 pm: Longer Presentation(20 - 30min):</p> <p>Brief Intro to SvelteJS - Courtney Fay</p> <p>What is Svelte? What makes it different than other frameworks out there? How does it work under the hood? (I\'ll try to make any JS connections possible) Why is everyone so psyched about it? Is it really the next big thing? How can I get started on my first Svelte project?</p> <p>Court graduated from General Assembly\'s web dev program in Dec 2016. She spent 2017 helping make bank websites at IHS Markit, and just started her second dev job at a startup that she thinks has the potential to reduce the cost of healthcare in America.</p> <p>Socialize:</p> <p>We\'ll have beer and pizza! We\'ll also allow people to announce any job opportunities they may have at that time so you can socialize with potential applicants.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1568726880000,
      duration: 14400000,
      id: '264923536',
      name: 'Night of Museums - Denver Arts Week',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1572732000000,
      local_date: '2019-11-02',
      local_time: '16:00',
      updated: 1568730030000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 63,
      group: {
        created: 1408485352000,
        name: 'Let\'s Explore Colorado',
        id: 16495582,
        join_mode: 'open',
        lat: 39.7400016784668,
        lon: -104.9800033569336,
        urlname: 'Lets-Explore-Colorado',
        who: 'Explorers',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/Lets-Explore-Colorado/events/264923536/',
      description: '<p>Let\'s go enjoy a night out at regional museums.</p> <p>-----</p> <p>Denver\'s best museums are open late and admission is FREE between 5 and 10 p.m on Saturday, November 2nd.</p> <p>I am setting this up as a sandbox event where everyone can attend in any order or sequence (or as many museums as) they want. Personally, I can only attend 4-5 locations max before I tap out. Some folks will opt to take advantage of the free shuttles (info to be posted here shortly); I may be taking a Lyft rideshare which I am open to sharing so as to better manage arrival/departures from each location.</p> <p>Shuttle buses will stop at (or nearby) select museums, beginning at 5 p.m. from the shuttle stop between the Denver Museum of Nature &amp; Science and Denver Zoo and also from the Denver Art Museum. (Parking available in the Cultural Complex Garage.)</p> <p>* I will be posting the sequence/order that I intend to follow that night within the next two weeks or so.</p> <p>-----</p> <p>GENERAL PLAN:</p> <p>Gather at least one hour ahead at a local watering hole - 4PM</p> <p>Free Night of Museums begins - 5PM</p> <p>-----</p> <p>BLACK AMERICAN WEST MUSEUM<br/>Watch African-American history come alive through re-enactments, videos, pictures and artifacts throughout this museum that depicts what life was like in Five Points, Colorado and the West.</p> <p>CENTER FOR COLORADO WOMEN\'S HISTORY AT BYERS-EVANS HOUSE MUSEUM<br/>Experience this historic landmark where expert tour guides will share the stories of the home and its residents in the 1900s.</p> <p>THE CELL<br/>Explore the interactive Counterterrorism Education Learning Lab to learn more about what you can do to help enhance community safety.</p> <p>CLYFFORD STILL MUSEUM<br/>See Still: Elemental, inspired by the perennial elements, and visit The Making Space to create your own Still-inspired artwork.</p> <p>DENVER ART MUSEUM<br/>Check out exhibitions for free, including The Light Show and Treasures of British Art. Stop by the Print Studio for some hands-on creativity!</p> <p>DENVER FIREFIGHTERS MUSEUM<br/>Discover one of the hottest, family-friendly places in town, and learn about the history of firefighting.</p> <p>DENVER MUSEUM OF NATURE &amp; SCIENCE<br/>See local artists activate spaces with light, sound, movement, color, story and passion - uniting the arts with nature and science in the museum\'s wildlife halls during DioramART.</p> <p>FORNEY MUSEUM OF TRANSPORTATION<br/>Stroll through this one-of-a-kind collection and explore the grace, space and pace of Jaguar with a selection of cars from the 1930s to the 1980s.</p> <p>HISTORY COLORADO CENTER<br/>Experience historic exhibits including Beer Here! Brewing the New West featuring meal deals and a flight of curated Colorado beers.</p> <p>KIRKLAND MUSEUM OF FINE &amp; DECORATIVE ART<br/>Explore Colorado\'s art history displayed with international decorative art in a unique setting, featuring Colorado Abstract +10: A History &amp; A Survey. (Children 13 and older welcome.)</p> <p>MOLLY BROWN HOUSE MUSEUM<br/>Tour the home of Denver\'s unsinkable Margaret Molly Brown, who was a world-renowned activist, performer and traveler. You may even see Mrs. Brown herself!</p> <p>MUSEO DE LAS AMERICAS<br/>Learn about the diverse arts and culture of the Americas from ancient to contemporary, through innovative exhibitions and programs.</p> <p>-----</p> <p>MORE MUSEUMS OPEN FOR FREE DURING NIGHT AT THE MUSEUMS*<br/>DINOSAUR RIDGE<br/>Discover the nation\'s #1 dinosaur track site on a guided flashlight tour, and head inside the exhibit hall for dinosaur and fossil crafts for all ages.</p> <p>FOUR MILE HISTORIC PARK<br/>Party like it\'s 1859 at a mini-hoedown! Enjoy tales told around a campfire and learn some popular American barn dances.</p> <p>MUSEUM OF OUTDOOR ARTS - MOA<br/>Register for your free tickets to the acclaimed Natura Obscura, an immersive art experience. Discover a journey you never though you\'d have.</p> <p>WINGS OVER THE ROCKIES AIR &amp; SPACE MUSEUM<br/>Immerse yourself in aviation history! Walk alongside majestic former warbirds, explore open cockpits and take a guided tour.</p> <p>*Free transportation shuttles are not available to all museums, and hours of operation may differ.*</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1412009588000,
      id: 'dlndskyznbhc',
      name: 'Yes, It\'s a Time Warp...and annual tradition...RHPS!',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1572068700000,
      local_date: '2019-10-25',
      local_time: '23:45',
      updated: 1412009588000,
      utc_offset: -21600000,
      waitlist_count: 2,
      yes_rsvp_count: 20,
      venue: {
        id: 663883,
        name: 'Esquire Theater',
        lat: 39.725433349609375,
        lon: -104.97289276123047,
        repinned: false,
        address_1: '590 Downing St',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '80218',
        state: 'CO'
      },
      group: {
        created: 1330729865000,
        name: 'Trails and Ales',
        id: 3404142,
        join_mode: 'open',
        lat: 39.70000076293945,
        lon: -105.08000183105469,
        urlname: 'Trails-and-Ales-etc',
        who: 'members',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/Trails-and-Ales-etc/events/dlndskyznbhc/',
      description: '<p>Have you seen the Rocky Horror Picture Show movie? Have you seen the movie with a live shadow cast aping the movie at the same time? Have you been dancing the Time Warp? Signing along to the songs, adding explicitly delightful lyrical changes? Do you have any idea what the hell we\'re referring too? Yes or no, come to show and partake in the debauchery that is the Rocky Horror Picture Show presented by Colorado\'s Elusive Ingredient! A loving couple, a few lost monsters and a sweet transvestite from transsexual Transylvania sing and dance through a campy, sloppy salute to horror movies and sexual liberation. Bring your sense of humor. And some toast.</p> <p>Bring yourself, bring a friend, dress for the occasion...or not...but bring some toast , a roll of toliet paper and some newspaper..)</p> <p>both the American producer, Lou Adler, and the British producer, Michael White, approached Richard O’Brien about transferring The Rocky Horror Show to celluloid. The producers agreed that the only person who should perform the character of Frank would have to be the original actor, Tim Curry. Curry, convinced by O’Brien and Quinn, who was reprising her original character of Magenta, began his first film production along with American actress Susan Surandon and American Broadway actor Barry Bostwick playing the rolls of Janet Weiss and Brad Majors. The American rock star, Meatloaf, would also rejoin the Rocky Horror world, playing the roll of Eddie, the Ex-Delivery boy, which he played on the Roxy Cast. (Piro, 1990, VII)</p> <p>With the production of the movie complete, Twentieth Century Fox Film Corporation released the film to a few key cities in late September, 1975. With the exception of Los Angeles, the movie was considered a failure to the general public, and was subsequently shelved with no thought given to a mass release. Collecting Dust, the movie reels sat until April 1st, 1976, when a young Fox executive, Tim Deegan, convinced the Waverly Theater in New York City to play it as the Midnight Feature. With this fortuitous event, The Rocky Horror Picture Show was on its way to infamy, stardom, and immortality. (Piro, 1990, VII)</p> <p>The Audience of the Waverly was already into the whole midnight movie phenomenon, booing villains and generally ignoring the common rules of etiquette that apply to standard movie goers. The theater played the record soundtrack of the movie before every showing, and the group of late night movie goers began to form together. This was the birthplace of Audience Participation, birthed from the creativity and sleep deprived minds of the Waverly Regulars. The pioneers of the audience participation were Louis Farese, credited with the first call back lines, a verbal line yelled at the screen from the audience, included “Buy an umbrella, you cheap bitch!” for when Janet walked through the rain up to the castle, and “How Strange was it?” directed at Chucky during his original opening speech. Farese was impressed to yell his first line on Labor Day weekend, 1976. Farese was not alone in the creation of the cult, Bill O’Brien was the first to dress up in costume, dressing up as Doctor Frank n’ Furter. The character play came to a culmination on Halloween of 1976, when a number of the audience members showed up in costume, and O’Brien and a few other regulars of the Waverly began to lip sink to the soundtrack recordings. “This was spontaneous and it developed into a mini-floor show before the movie. Audience response was tremendous.” (Piro, 1990)</p>',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '19:00',
      local_date: '2019-11-20',
      link: 'https://www.meetup.com/Denver-30s-40s-Professionals/events/265578781/',
      visibility: 'public_limited',
      group: {
        created: 1517544020000,
        name: 'Denver 30s/40s Professionals',
        id: 27352376,
        join_mode: 'approval',
        lat: 39.77000045776367,
        lon: -105.01000213623047,
        urlname: 'Denver-30s-40s-Professionals',
        who: 'Professionals',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      waitlist_count: 0,
      yes_rsvp_count: 8,
      duration: 10800000,
      time: 1574301600000,
      utc_offset: -25200000,
      name: '--->>>>-----Skating into Winter---->>>>----',
      id: '265578781'
    },
    {
      created: 1563478026000,
      duration: 7200000,
      id: '263267074',
      name: 'Don Quixote Colorado Ballet',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1570996800000,
      local_date: '2019-10-13',
      local_time: '14:00',
      rsvp_close_offset: 'PT672H',
      updated: 1568225999000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 17,
      venue: {
        id: 26024978,
        name: 'Ellie Caulkins Opera House at Denver Performing Arts Complex',
        lat: 39.744964599609375,
        lon: -104.99736022949219,
        repinned: true,
        address_1: '1385 Curtis Street',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '80204',
        state: 'CO'
      },
      group: {
        created: 1434561971000,
        name: 'Classical Connection',
        id: 18679951,
        join_mode: 'open',
        lat: 39.70000076293945,
        lon: -105.08000183105469,
        urlname: 'Classical-Connection',
        who: 'Cool Classics',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/Classical-Connection/events/263267074/',
      description: '<p>Price for our regular seats is $40.00 and you must pay with in one week of your rspv. I will set up another event before this ballet when the time is closer for a brunch. our seats are on the main floor, just above the horseshoe on the right as you look at the stage. I must pay for this event before Sept. 20th or give up all unsold seats.</p> <p>Follow Don Quixote and Sancho Panza as they search for a noble adventure, which leads to a band of gypsies, dreams of Dryads and a surprising turn of events. Don Quixote remains one of today’s most frequently performed romantic works with classical choreography by Marius Petipa, along with stunning Spanish sets and costumes.</p> <p>If you do not contact me to pay within 7 days I will remove you from this event.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1564181675000,
      duration: 10800000,
      id: 'rsgkjryznbmc',
      name: 'Monthly Game Night At Stoneys',
      rsvp_limit: 100,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1572399000000,
      local_date: '2019-10-29',
      local_time: '19:30',
      updated: 1569357957000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 41,
      venue: {
        id: 26021223,
        name: 'Stoney\'s Bar and Grill',
        lat: 39.73430252075195,
        lon: -104.9863052368164,
        repinned: true,
        address_1: '1111 Lincoln St',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '80203',
        state: 'CO'
      },
      group: {
        created: 1562509978000,
        name: 'Denver Fun 20s and 30s',
        id: 32336529,
        join_mode: 'open',
        lat: 39.7400016784668,
        lon: -104.9800033569336,
        urlname: 'DenverFun',
        who: 'Machiavellian Meerkats',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/DenverFun/events/rsgkjryznbmc/',
      description: '<p>Location is STONEY\'S - and on Taco Tuesday too! Please check in for name tags.</p> <p>Please bring a game to share, and feel free to come early for some tacos.<br/>We\'ll have a space to ourselves, but since all the games are what we bring as a group - its important we bring them!</p> <p>Small, social games that support lots of players are usually best, or if you have a serious game in mind, you easily break off and use one of the booths.</p> <p>We usually charge $1 per person to raise event money. No fee if you have no job, are student-debt broke, or simply can\'t afford it. Want to know where our money goes? Just ask! We\'re accountable to our members, and some of our members (and leaders!) are accountants.</p> ',
      how_to_find_us: 'Ask at the entrance or read the comments, as our seating changes monthly.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '18:30',
      local_date: '2019-10-17',
      link: 'https://www.meetup.com/Denver-30s-40s-Professionals/events/264447407/',
      visibility: 'public_limited',
      group: {
        created: 1517544020000,
        name: 'Denver 30s/40s Professionals',
        id: 27352376,
        join_mode: 'approval',
        lat: 39.77000045776367,
        lon: -105.01000213623047,
        urlname: 'Denver-30s-40s-Professionals',
        who: 'Professionals',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      waitlist_count: 0,
      yes_rsvp_count: 13,
      duration: 7200000,
      time: 1571358600000,
      utc_offset: -21600000,
      name: 'Denver Brewery Explorer: Tivoli Brewing Company ',
      id: '264447407'
    },
    {
      created: 1543264725000,
      duration: 7200000,
      id: 'kgrmmqyznbtb',
      name: 'Using React Hooks for Global State && Lightning Talks ⚡️',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1571184000000,
      local_date: '2019-10-15',
      local_time: '18:00',
      updated: 1570748421000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 96,
      group: {
        created: 1430233872000,
        name: 'React Denver',
        id: 18567495,
        join_mode: 'open',
        lat: 39.75,
        lon: -104.98999786376953,
        urlname: 'ReactDenver',
        who: 'Developers',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/ReactDenver/events/kgrmmqyznbtb/',
      description: '<p>Come downtown for food, drink, talks, and socializing. We\'ll be talking about ReactJS and related technologies. Talks/topics to be covered:</p> <p>Using React Hooks for Global State by Patrick Goulding</p> <p>Patrick will be going over how to use react hooks to change your class based components into functional components, and getting rid of Redux.</p> <p>and Lightning Talks!</p> <p>⚡️If you\'d like to give a lightning talk, please sign up here!</p> <p>docs.google.com/forms/d/e/1FAIpQLSf2fYsSKPuQXMDchAkAiTMfl-NKYUqqlVUzWGr2ZoncK68uZw/viewform</p> <p>A huge thanks to our event sponsor, Pana!<br/>Check them out at www.pana.com</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1558711008000,
      duration: 7200000,
      id: 'tzlcbryznbtb',
      name: 'Denver Python Meetup - Downtown',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1571184000000,
      local_date: '2019-10-15',
      local_time: '18:00',
      updated: 1558711008000,
      utc_offset: -21600000,
      waitlist_count: 3,
      yes_rsvp_count: 10,
      venue: {
        id: 26081986,
        name: 'Denver Milk Market',
        lat: 39.753108978271484,
        lon: -104.99727630615234,
        repinned: true,
        address_1: '1800 Wazee St #100',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '80202',
        state: 'CO'
      },
      group: {
        created: 1343167529000,
        name: 'Women Who Code Boulder/Denver',
        id: 4385962,
        join_mode: 'open',
        lat: 39.70000076293945,
        lon: -104.95999908447266,
        urlname: 'Women-Who-Code-Boulder-Denver',
        who: 'Women Who Code Members',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/Women-Who-Code-Boulder-Denver/events/tzlcbryznbtb/',
      description: '<p>This is a study group meetup for people looking to learn python. All experience levels welcome. We meet in Milk Market at the long table near the Hotel front desk. I usually have pink/purple/blue hair so we are easy to find.</p> <p>6:00 - 8:00 Work on personal/work projects and get help from others.</p> <p>If you don\'t have a personal project, I can suggest the problem sets on www.w3resource.com/python-exercises/ and will select a level based on the experience level of the group.</p> <p>Homework, beginner, and advanced questions always welcome.</p> <p>Women Who Code isn\'t just for women, anyone is welcome.</p> ',
      how_to_find_us: 'We meet in Milk Market at the long table near the Hotel front desk. I usually have pink/purple/blue hair so we are easy to find.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1566766005000,
      duration: 16200000,
      id: '264296545',
      name: 'Halloween Party',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1572138000000,
      local_date: '2019-10-26',
      local_time: '19:00',
      updated: 1566766005000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 90,
      venue: {
        id: 26478194,
        name: 'Knights of Columbus',
        lat: 39.74112319946289,
        lon: -104.9839859008789,
        repinned: false,
        address_1: '1555 Grant St',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '80203',
        state: 'CO'
      },
      group: {
        created: 1511105928000,
        name: '5280 Singles Over 40',
        id: 26643716,
        join_mode: 'open',
        lat: 39.70000076293945,
        lon: -105.08000183105469,
        urlname: '5280-Singles-Over-40',
        who: 'Motivated Singles',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/5280-Singles-Over-40/events/264296545/',
      description: '<p>It\'s that time of year again to go out and party like your someone else...or at least dressed like someone else. Our Halloween Party is open to all ages over 21 and has more fun people than you can find almost anywhere on this night. We have lots of things to do including getting some free parking near downtown, a best costume prize of $50 cash for the best man\'s and best woman\'s costume, one free drink and snacks, a free dance lesson at 7:30 pm, a mixer for singles and dancing to our new DJ until 11:30 pm. Admission is only $15 cash per person. Present your 5280 Singles Membership card at the door to receive $5 off admission or visit our website at www.5280singles.org to pre-purchase your ticket(s) at a discount before 10/15/19. All in all, a value of over $25 for only $15 or less and a great time with some fun people. No costume or dressing up is required, but nearly any kind of out of the ordinary outfit could be fun. Park in front of the building or at the other Star Parking lot at 16th and Sherman St. and don\'t pay the slot on the box after 6 pm.</p> ',
      how_to_find_us: 'We reserved the whole building.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1518040897000,
      duration: 7200000,
      id: 'nprrhpyznbwb',
      name: 'Meet NestJS with Ely Lucas - Node.js Denver/Boulder/Ft. Collins',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1571963400000,
      local_date: '2019-10-24',
      local_time: '18:30',
      updated: 1569933604000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 26,
      venue: {
        id: 25218113,
        name: 'Code Talent',
        lat: 39.76769256591797,
        lon: -104.97679138183594,
        repinned: true,
        address_1: '3412 Blake St',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '',
        state: 'CO'
      },
      group: {
        created: 1390239907000,
        name: 'Node.js Denver/Boulder/Ft. Collins',
        id: 12305542,
        join_mode: 'open',
        lat: 39.75,
        lon: -104.98999786376953,
        urlname: 'Node-js-Denver-Boulder',
        who: 'Members',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/Node-js-Denver-Boulder/events/nprrhpyznbwb/',
      description: '<p>Talk:</p> <p>Meet NestJS with Ely Lucas</p> <p>Nest is a server-side framework for Node, that uses modern language features (via TypeScript) to create efficient, reliable, and scalable apps. The popularity of Nest has been exploding lately as developers are discovering how easy and powerful it is to build server-side applications with it. Front end developers are finding it especially easy to dive into full-stack development with Nest, while backend developers from other frameworks are finding familiar features they expect from a top-class web framework. In this talk, we will get introduced to Nest and discover how to create a simple, yet functional, API with it.</p> <p>---</p> <p>Speaker:</p> <p>Ely Lucas<br/>@elylucas</p> <p>Ely is a web and mobile developer living in Denver, CO with his wife, four kids, and dog. He works at Ionic as a software engineer and developer advocate and loves all things web. When not coding, he enjoys learning new tech and sharing with others.</p> <p>---</p> <p>Schedule:</p> <p>6:30pm: Pizza, beer, networking<br/>7:00pm: Talk<br/>7:45pm: Questions</p> <p>Hope you all can make it out to this great talk. If you have any questions, don\'t hesitate to reach out.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1570728189000,
      duration: 5400000,
      id: '265565275',
      name: 'What\'s the big deal about Angular Pipes?',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1571788800000,
      local_date: '2019-10-22',
      local_time: '18:00',
      updated: 1570728189000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 11,
      venue: {
        id: 25150694,
        name: 'BrieBug',
        lat: 39.713462829589844,
        lon: -105.13997650146484,
        repinned: false,
        address_1: '12596 W Bayaud Ave',
        address_2: 'Suite 201',
        city: 'Lakewood',
        country: 'us',
        localized_country_name: 'USA',
        zip: '80228',
        state: 'CO'
      },
      group: {
        created: 1367467789000,
        name: 'Rocky Mountain Angular',
        id: 8311872,
        join_mode: 'open',
        lat: 39.70000076293945,
        lon: -104.95999908447266,
        urlname: 'RockyMountainAngular',
        who: 'Angulars',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/RockyMountainAngular/events/265565275/',
      description: '<p>5:30- Doors Open🍻🍕<br/>6:00- Announcements 📣<br/>6:15- What\'s the big deal about Angular Pipes 🤯<br/>7:30- Wrap Up 👋🏽</p> <p>Jesse Sanders, our local Angular and Web Technologies GDE, will be presenting on what are Angular Pipes and why you should care. Most Angular developers know about pipes, but often don\'t understand the why behind them. This 40-minute hands-on presentation will guide you on what are pipes, how to use the most common ones, when you should create a custom pipe, and what are some of the pitfalls and performance gotchas. If you\'re still using functions to format your data in your HTML this is a must-watch presentation that will dramatically increase your application performance.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '13:00',
      local_date: '2019-12-01',
      link: 'https://www.meetup.com/Adventurous-Women-Outdoors-and-Indoors/events/264461996/',
      visibility: 'public_limited',
      group: {
        created: 1280421947000,
        name: 'Adventurous Women',
        id: 1682728,
        join_mode: 'open',
        lat: 39.900001525878906,
        lon: -105,
        urlname: 'Adventurous-Women-Outdoors-and-Indoors',
        who: 'Adventurous Women',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      waitlist_count: 0,
      yes_rsvp_count: 30,
      duration: 10800000,
      time: 1575230400000,
      utc_offset: -25200000,
      name: 'Annual AW Holiday Party',
      id: '264461996'
    },
    {
      created: 1570132867000,
      duration: 7200000,
      id: '265383654',
      name: 'Session 2: SignUp / SignIn: Angular 8 and Material Overviews + Component Code',
      rsvp_limit: 15,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1571875200000,
      local_date: '2019-10-23',
      local_time: '18:00',
      updated: 1570132934000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 10,
      venue: {
        id: 26053847,
        name: 'Galvanize - Denver (Platte)',
        lat: 39.75765609741211,
        lon: -105.00695037841797,
        repinned: true,
        address_1: '1644 Platte St',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '80202',
        state: 'CO'
      },
      group: {
        created: 1507576102000,
        name: 'Coding for the Web',
        id: 26209918,
        join_mode: 'open',
        lat: 39.7400016784668,
        lon: -105.0199966430664,
        urlname: 'Coding-for-the-Web',
        who: 'Members',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/Coding-for-the-Web/events/265383654/',
      description: '<p>In this session we will dive into the file structure of our Angular 8 app. We will also be looking into the features of Angular Material for our UI elements. We will then be using some of those features as we build the UI for the SignIn and SignUp components of our app. If there is extra time, we may begin talking about the basics of AWS Lambda for our API.</p> <p>If you\'re joining, and want to follow along on your laptop, feel free to download this Git repo: github.com/jmarkyston/coding-for-the-web-2019</p> <p>I will check in at the beginning of the session to see if anybody has had issues downloading the repo. If so, we may spend some time talking about Git before getting into the Angular stuff.</p> <p>Typically, these sessions will happen every 2 weeks. Unfortunately, Galvanize has large events going on when this session was planned, so we\'re looking at an additional 2 weeks out for this session.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '14:00',
      local_date: '2019-11-16',
      link: 'https://www.meetup.com/Denver-30s-40s-Professionals/events/264854955/',
      visibility: 'public_limited',
      group: {
        created: 1517544020000,
        name: 'Denver 30s/40s Professionals',
        id: 27352376,
        join_mode: 'approval',
        lat: 39.77000045776367,
        lon: -105.01000213623047,
        urlname: 'Denver-30s-40s-Professionals',
        who: 'Professionals',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      waitlist_count: 0,
      yes_rsvp_count: 18,
      duration: 10800000,
      time: 1573938000000,
      utc_offset: -25200000,
      name: 'Urban Winery Explorer @ Bigsby’s Folly ',
      id: '264854955'
    }
  ]
};

export { mockEvents };